# Hotplugs
obj-$(CONFIG_AIO_HOTPLUG)	+= aio_hotplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) 	+= alucard_hotplug.o
obj-$(CONFIG_ASMP)		+= autosmp.o
obj-$(CONFIG_BRICKED_HOTPLUG)   += bricked_hotplug.o
obj-$(CONFIG_CLUSTER_HOTPLUG)   += cluster_hotplug.o
obj-$(CONFIG_INTELLI_HOTPLUG)	+= intelli_hotplug.o
obj-$(CONFIG_MAKO_HOTPLUG) 	+= mako_hotplug.o
